# Python CircleCI 2.0 configuration file
# Updating CircleCI configuration from v1 to v2
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: update
          command: |
            pip install --upgrade pip
      - run:
          name: install
          command: |
           sudo -H pip install jupyter
           sudo jupyter notebook
      - run:
          name: smoke test jupyterhub
          command: |
            curl -s http://whatismyip.akamai.com/
            sudo jupyter notebook --allow-root
      - run:
          name: verify static files
          command: |
            jupyter-lab

# Tell CircleCI to use this workflow when it builds the site
workflows:
  version: 2
  default:
    jobs:
      - build
